-- U12: Reverter conversao de VARCHAR para TEXT

ALTER TABLE usuario ALTER COLUMN name TYPE VARCHAR(255);
ALTER TABLE cultura ALTER COLUMN nome TYPE VARCHAR(255);
ALTER TABLE tarefa ALTER COLUMN titulo TYPE VARCHAR(255);
ALTER TABLE preco_mercado ALTER COLUMN produto TYPE VARCHAR(255);
ALTER TABLE notificacao ALTER COLUMN titulo TYPE VARCHAR(255);
ALTER TABLE notificacao ALTER COLUMN mensagem TYPE VARCHAR(500);
ALTER TABLE insumo ALTER COLUMN nome TYPE VARCHAR(255);
ALTER TABLE insumo ALTER COLUMN fornecedor TYPE VARCHAR(255);
ALTER TABLE movimento_estoque ALTER COLUMN motivo TYPE VARCHAR(255);
ALTER TABLE movimento_estoque ALTER COLUMN responsavel TYPE VARCHAR(255);
